apiVersion: apps/v1
kind: Deployment
metadata:
    name: kubernetes-volumes
spec:
    replicas: 3
    selector:
        matchLabels:
            deployment: kubernetes-volumes
    template:
        metadata:
            labels:
                deployment: kubernetes-volumes
        spec:
            containers:
                - name: kubernetes-volumes
                  image: mroranger/kubernetes-volumes:1
                  volumeMounts:
                      - mountPath: /var/www/books
                        name: book-volumes
            volumes:
                - name: book-volumes
                  hostPath:
                      path: /var/www/data
                      type: DirectoryOrCreate
