apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-volume-claim
spec:
  volumeName: book-volume
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
