version: '3.8'
name: course-management-databases

services:
    professors-database:
        container_name: professors
        build:
            context: ./professor
            dockerfile: database.dockerfile
        ports:
            - 3000:3306
        env_file:
            - ./professor/.env
        networks:
            - course-management-network
        volumes:
            - database-professor-volume:/var/lib/mysql

    courses-database:
        container_name: courses
        build:
            context: ./course
            dockerfile: database.dockerfile
        ports:
            - 3001:3306
        env_file:
            - ./course/.env
        networks:
            - course-management-network
        volumes:
            - database-course-volume:/var/lib/mysql

    students-database:
        container_name: students
        build:
            context: ./student
            dockerfile: database.dockerfile
        ports:
            - 3002:3306
        env_file:
            - ./student/.env
        networks:
            - course-management-network
        volumes:
            - database-student-volume:/var/lib/mysql

networks:
    course-management-network:
        driver: bridge

volumes:
    database-professor-volume:
    database-course-volume:
    database-student-volume:
