apiVersion: v1
kind: Service
metadata:
    name: clients-database-service
spec:
    type: ClusterIP
    selector:
        statefulset: clients-database-statefulset
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3306
