apiVersion: v1
kind: ConfigMap
metadata:
    name: orders-database-configmap
data:
    DATABASE_HOST: 'orders-database-service.default'
    DATABASE_PORT: '3001'
    DATABASE_TYPE: 'mysql'
    DATABASE_ROOT_USER: 'root'
    DATABASE_ROOT_PASSWORD: 'root@2025'
    DATABASE_USER: 'admin'
    DATABASE_PASSWORD: 'admin@@2025'
    DATABASE_NAME: 'orders'
    TZ: 'Europe/Rome'
