apiVersion: v1
kind: Service
metadata:
    name: products-database-service
spec:
    type: ClusterIP
    selector:
        statefulset: products-database-statefulset
    ports:
        - protocol: TCP
          port: 3002
          targetPort: 3306
