apiVersion: v1
kind: PersistentVolume
metadata:
    name: orders-database-volume
spec:
    storageClassName: manual
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data/kubernetes/orders'
