apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clients-database-volume-claim
    labels:
        database: mysql
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi
